import scrapy

class JozekSpider(scrapy.Spider):
    name = 'JozekSpider'
    start_urls = [
        # Generated by link extractor
        #TODO: Eventually make a script to do this for me
        'https://shopmiler.com/pl/wyprzedaz/',
        'https://shopmiler.com/pl/garnitury',
        'https://shopmiler.com/pl/koszule-meskie',
        'https://shopmiler.com/pl/koszulki-polo/koszulka-polo-biala-kp-1-1',
        'https://shopmiler.com/pl/kurtki/granatowa-kurtka-pikowana',
        'https://shopmiler.com/pl/marynarki',
        'https://shopmiler.com/pl/obuwie',
        'https://shopmiler.com/pl/spodnie',
        'https://shopmiler.com/pl/swetry',
        'https://shopmiler.com/pl/akcesoria/krawaty',
        'https://shopmiler.com/pl/akcesoria/poszetki',
        'https://shopmiler.com/pl/akcesoria/paski',
        'https://shopmiler.com/pl/akcesoria/wieszaki',
        'https://shopmiler.com/pl/akcesoria/muszki',
        'https://shopmiler.com/pl/akcesoria/kaszkiety',
        'https://shopmiler.com/pl/akcesoria/szelki',
        'https://shopmiler.com/pl/akcesoria/rekawiczki',
        'https://shopmiler.com/pl/akcesoria/szale',
        'https://shopmiler.com/pl/akcesoria/kieliszki',
        'https://shopmiler.com/pl/torby',
        'https://shopmiler.com/pl/akcesoria/spinki-do-mankietow',
        'https://shopmiler.com/pl/akcesoria/degustacja',
        'https://shopmiler.com/pl/akcesoria/karty-podarunkowe'
    ]

    def parse(self, response):
        for product in response.css('div.category-product'):
            yield {
                'product-name': product.css('div::text').extract(),
                'old-price': product.css('del::text').extract_first(),
                'price': product.css('span::text').extract_first()
                #TODO: Get images (thumbnails)
            }
        next_page = response.css('li.last a::attr("href")').extract_first()
        if next_page is not None:
            yield response.follow(next_page, self.parse)

        #TODO: Get output already nicely formatted